Powsup 18 creare sezione gestione homepage
PowsUp/website pull request #116
Opened 2023-12-17 18:53 UTC by IsThisDemi

### Completato
- Aggiunta sezione news ed eventi recenti con contentful
- HeroBanner dati ottenuti con contentful

### Da decidere
- Guarda gli eventi e notizie link singolo (quale dei due?) o separati

2023-12-19 07:45 UTC, CatMonster requested changes

2023-12-19 07:45 UTC, CatMonster commented on src/components/widgets/HeroHome.astro
>            {title && <h1 class="text-4xl font-bold tracking-tight sm:text-6xl dark:text-gray-200" set:html={title} />}
Controllando il campo `title` dell'home banner, ho notato che hai usato il campo di tipo `long text`.
Non credo che sia appropriato visto che è un titolo abbastanza corto, ma penso che l'abbia usato perchè ti proponeva la text area con il supporto alle new lines. L'unico problema è per ogni new line, ti crea un nuovo paragrafo, di per sè non sarebbe un problema, ma essendo il titolo della pagina stiamo di conseguenza stampando due paragrafi in un h1.
<img width="1506" alt="image" src="https://github.com/PowsUp/website/assets/13244343/72faa7b9-bd17-4545-8d7b-1a9e01f868ce">
Per questioni di seo dobbiamo mantenere l'h1, quindi possiamo provare a cambiarlo in un campo di tipo `rich text` e abilitare solo l'h1. In questo modo i copy possono mantenere l'html valido

2023-12-19 07:45 UTC, CatMonster commented on src/types/CtaItemModel.ts
> +    targetType?: '_self' | '_blank';
Se non sbaglio lo hai messo required nel modello di contentful, come mai qua è opzionale?

2023-12-19 07:45 UTC, CatMonster commented on src/components/widgets/BlogLatestPosts.astro
> +const newsPost1 = items1.map((item) => {
Possiamo chiamarlo `latestNews`?

2023-12-19 07:45 UTC, CatMonster commented on src/components/widgets/BlogLatestPosts.astro
> +const newsPost2 = items2.map((item) => {
Possiamo chiamarlo `latestMeets`?

2023-12-19 18:44 UTC, IsThisDemi commented on src/types/CtaItemModel.ts
> +    targetType?: '_self' | '_blank';
Giusto! all'inizio l'avevo impostato come blank o vuoto (opzionale) ora lo tolgo

2023-12-19 18:45 UTC, IsThisDemi commented on src/components/widgets/BlogLatestPosts.astro
> +const newsPost1 = items1.map((item) => {
Si molto meglio

2023-12-19 18:45 UTC, IsThisDemi commented on src/components/widgets/BlogLatestPosts.astro
> +const newsPost2 = items2.map((item) => {
Si o nel caso latestEvents

2023-12-30 14:18 UTC, CatMonster requested changes

2023-12-30 14:18 UTC, CatMonster commented on .vscode/settings.json
> +    "editor.defaultFormatter": "ms-vsliveshare.vsliveshare"
questa modifica non era da committare

2023-12-30 14:20 UTC, CatMonster commented
Non ho capito 

> Da decidere: Guarda gli eventi e notizie link singolo (quale dei due?) o separati

Intendi questa sezione?
<img width="1419" alt="image" src="https://github.com/PowsUp/website/assets/13244343/ad74555b-4e77-4ae0-b0f0-898d35f624b0">

Se si avevamo già discusso a riguardo, prendere tre elementi tra post e meet recenti.
Forse il tuo commento è outdated?

2024-01-02 14:32 UTC, IsThisDemi commented
> Non ho capito
> 
> > Da decidere: Guarda gli eventi e notizie link singolo (quale dei due?) o separati
> 
> Intendi questa sezione? <img alt="image" width="1419" src="https://private-user-images.githubusercontent.com/13244343/293464956-ad74555b-4e77-4ae0-b0f0-898d35f624b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDU5NTYsIm5iZiI6MTcwNDIwNTY1NiwicGF0aCI6Ii8xMzI0NDM0My8yOTM0NjQ5NTYtYWQ3NDU1NWItNGU3Ny00YWUwLWIwZjAtODk4ZDM1ZjYyNGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE0MjczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0M2I2MzhkMTk0MWE4ODJmZWRjZTE2MGZlYjAyZGE3ZmExNGJkMzY4YjEyODI3M2U2NDIxMjkzMTAwZGUyM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z8cgqARbJ0H1Se2OJxY4WxKywWc5qfRP9i2jO7pt-R0">
> 
> Se si avevamo già discusso a riguardo, prendere tre elementi tra post e meet recenti. Forse il tuo commento è outdated?

Sisi lo abbiamo già risolto

2024-01-02 22:08 UTC, CatMonster approved these changes

2024-01-02 22:08 UTC, merged