404 page
PowsUp/website pull request #18
Opened 2023-09-21 17:40 UTC by IsThisDemi

### Realizzazione pagina 404
- Utilizzato il component https://tailwindui.com/components/marketing/feedback/404-pages#component-ebef3404d06e7b5f42e85b7b2ca4a2a5
- Il colore e lo stile si basano sui colori base dello stile di tailwind e la class btn

2023-09-22 21:21 UTC, JaxzTW approved these changes
Niiiice job

2023-09-23 05:03 UTC, CatMonster requested changes

2023-09-23 15:32 UTC, IsThisDemi commented on src/pages/404.astro
> +  <main class="grid min-h-full place-items-center px-6 py-24 sm:py-32 lg:px-8">
cambiato a section, con i nuovi colori i pulsanti sono illeggibili modifico la classe btn

2023-09-23 15:34 UTC, IsThisDemi commented
prima di fare merge su develop sistemo i pulsanti che sono illeggibili

2023-09-23 17:15 UTC, IsThisDemi commented
Modificato i colori dei pulsanti per renderli più leggibili, se vanno bene possiamo metterli come classe btn-primary e settarli di default sul resto del sito

2023-09-26 18:27 UTC, CatMonster commented on src/pages/404.astro
> +        <a
Potremmo fare una prova ed usare il componente `Button`?

2023-09-27 17:00 UTC, IsThisDemi commented on src/pages/404.astro
> +        <a
Giusto ora usa il componente `Button`

2023-09-28 06:06 UTC, CatMonster approved these changes

2023-09-28 06:06 UTC, merged