Footer component
PowsUp/website pull request #21
Opened 2023-09-23 17:24 UTC by IsThisDemi

### Creato il component del footer
La struttura è fatta, restano due cose da implementare 

- una volta finite pagine e categorie basta inserirle nel footerData in navigation.js
- sostituire logoImage (con un link al cms (?) o direct)

2023-09-24 14:37 UTC, JaxzTW commented
Navigation.js l'ho modificato io con quello che potrebbe servirci, andranno solo rivisti i href per renderli funzionanti
Per il logo è da capire se con cms o file/link

2023-09-26 18:32 UTC, CatMonster requested changes

2023-09-26 18:32 UTC, CatMonster commented on src/navigation.js
> +    © PawsUp 2023 | Grazie a volontari ❤️
Errore di spelling, PowsUp è corretto.
Mettiamo l'anno dinamico? Prova a prendere spunto dalla landing.

2023-09-27 17:18 UTC, IsThisDemi commented
Corretto lo spelling, messo la data dinamica in `navigation.js `, manca solo da decidere come mettere l'icona dell'immagine

2023-09-28 06:17 UTC, CatMonster requested changes

2023-09-28 06:17 UTC, CatMonster commented on src/navigation.js
> +    © PowsUp `+currentYear+` | Grazie a volontari ❤️
Spelling, "...Grazie ai volontari..."

Prova ad usare le template literals sono molto più comode delle concatenazioni di stringhe
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

```js
`© PowsUp ${currentYear} | Grazie a volontari ❤️`
```

2023-09-28 06:17 UTC, CatMonster commented on src/components/widgets/Footer.astro
Rimuovi gli import inutilizzati

2023-09-28 06:18 UTC, CatMonster commented
@IsThisDemi per i loghi apro un altro issue

2023-09-28 13:09 UTC, IsThisDemi commented on src/navigation.js
> +    © PowsUp `+currentYear+` | Grazie a volontari ❤️
Ero abituato al php, più comodi questi 😸

2023-09-28 13:09 UTC, IsThisDemi commented on src/components/widgets/Footer.astro
Tolti

2023-09-28 20:36 UTC, JaxzTW commented
Aspetterei a cambiarlo, sabato valutiamo quale ci piace di più, quello che c'è di base anche non è male
![image](https://github.com/PowsUp/website/assets/67195101/ef3add26-f853-4eae-98ea-88dc1ec9920e)
![image](https://github.com/PowsUp/website/assets/67195101/a8dfa7a6-baa5-428b-abc7-6e5d3e106a75)

2023-09-30 16:43 UTC, CatMonster commented
@JaxzTW cosa facciamo con questa pr?

2023-09-30 16:46 UTC, JaxzTW commented
> @JaxzTW cosa facciamo con questa pr?

Volevo vederlo oggi, lo vedremo domani

2023-10-01 12:47 UTC, closed without merging