Home
PowsUp/website pull request #25
Opened 2023-09-29 21:10 UTC by JaxzTW

2023-09-30 16:59 UTC, CatMonster requested changes

2023-09-30 16:59 UTC, CatMonster commented on src/pages/index.astro
>    <BlogLatestPosts
Questo pezzo in modalità desktop sembra volante e non collegato a nulla
<img width="1503" alt="image" src="https://github.com/PowsUp/website/assets/13244343/6e248cc5-5c81-43d9-8004-cf3c4e0f8e94">
Non potremmo spostarlo o toglierlo del tutto?

2023-09-30 16:59 UTC, CatMonster commented on src/components/widgets/HeroHome.astro
https://github.com/PowsUp/website/assets/13244343/973979fc-0b93-4e49-97cd-d53bfe2f8ab9

Da 992 in giù c'è un comportamento strano del titolo dell'hero, da rivedere  l'allineamento

2023-09-30 18:40 UTC, JaxzTW commented on src/components/widgets/HeroHome.astro
Si ridimensiona, è "normale", non l'ho modificato dal componente originale

2023-09-30 18:40 UTC, JaxzTW commented on src/pages/index.astro
>    <BlogLatestPosts
Va bene lo nascondo nei dispositivi large

2023-09-30 18:52 UTC, JaxzTW commented
Risolto testo che fluttuava

2023-10-01 13:12 UTC, CatMonster commented on src/components/widgets/HeroHome.astro
eh ok, sistemiamo i vari breakpoint, così non è bello

2023-10-14 10:22 UTC, JaxzTW commented
La home per ora va bene così

2023-10-14 18:05 UTC, Shilvio approved these changes

2023-10-14 18:06 UTC, merged